name: finger_farm
description: "Finger Farm project."
publish_to: 'none'

version: 2.2.2+23

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # UI & Image
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.3.1
  shimmer_animation: ^2.2.2
  toggle_switch: ^2.3.0
  marquee: ^2.2.3
  gap: ^3.0.1
  fl_chart: ^0.68.0

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_analytics: ^11.4.4
  firebase_messaging: ^15.1.1
  cloud_firestore: ^5.0.2
  firebase_database: ^11.3.4

  # State Management & Navigation
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0

  # Network & Auth
  http: ^1.2.1
  google_sign_in: ^6.2.1
  thingsboard_client: ^1.2.1

  # Utilities
  collection: ^1.19.1
  connectivity_plus: ^6.1.3
  flutter_signal_strength: ^0.0.1
  intl: ^0.19.0
  intl_translation: ^0.20.0
  package_info_plus: ^8.1.2
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.0

dependency_overrides:
  # Fix for marquee dependency after Flutter 3.2.2 upgrade
  fading_edge_scrollview: ^4.1.1
  flutter_signal_strength: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/